### ISSUE TITLE
Compatibility with OpenJDK Zulu 11

### ISSUE THREAD

**Issue by Jens2205** [jlolling/talendcomp_tKarafService#3]
Hi, 
we encountered a problem by compiling the tKarafServiceList component with OpenJDK Zulu 11.0.15:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger
	at de.jlo.talendcomp.karaf.jmx.BaseClient.<clinit>(BaseClient.java:31)
	at sandbox.test_karaf_list_0_1.test_karaf_list.tKarafServiceList_1Process(test_karaf_list.java:417)
	at sandbox.test_karaf_list_0_1.test_karaf_list.runJobInTOS(test_karaf_list.java:987)
	at sandbox.test_karaf_list_0_1.test_karaf_list.main(test_karaf_list.java:757)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more
```
With Oracle-JDK 8 everything works fine, but we like to Update our environment.  

Thanks for your help and best regards!

**Comment by jlolling** [comment]
Which studio version do you running?

**Comment by Jens2205** [comment]
Talend Studio 7.3.1

**Comment by jlolling** [comment]
Which version (1 or 2) of log4j is set in your projects? Check that in the project settings please.

**Comment by Jens2205** [comment]
Log4j2 is selected:
![image](https://user-images.githubusercontent.com/29700391/174621288-62d3beb0-ed81-43df-aab7-f88e2b75eff7.png)

**Comment by jlolling** [comment]
In my Talend Studio 7.3.1 I have actually not this problem but I always replace the old log4j with the new log4j v2.
I am changing this just now and provide a new version in the next view minutes.

**Comment by Jens2205** [comment]
Thanks a lot for your very quick response and help! 😊

**Comment by jlolling** [comment]
Could you please check this release here?
https://github.com/jlolling/talendcomp_tKarafService/releases/tag/3.4
And I would be happy about feedback.

**Comment by Jens2205** [comment]
Thanks @jlolling! It works fine :-)
